version: '3.8'
services:
  keycloak:
    build: .
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=ADMIN
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KEYCLOAK_DEFAULT_THEME=veith
    command: start-dev
    volumes:
      - ./themes/veith:/opt/keycloak/themes/veith